version: '3.8'

services:
  semantic-croissant:
    build: .
    container_name: croissant-mcp
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MCP_BASE_URL=http://localhost:8000/mcp
      - "CACHEDIR"
      - "KAGGLE_USERNAME"
      - "KAGGLE_KEY"
      - "HF_API_KEY"
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/mcp"]
      interval: 30s
      timeout: 10s
      retries: 3
